/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdlib.h>
#include"Platform_Types.h"
#include"BIT_MATH.h"

/* register address */
#define RCC_BASE 			0x40021000
#define GPIOA_BASE 			0x40010800

#define RCC_APB2ENR 		*((vuint32_t*) (RCC_BASE + 0x18))
#define GPIOA_CRH 			*((vuint32_t*) (GPIOA_BASE + 0x04))
#define GPIOA_ODR 			*((vuint32_t*) (GPIOA_BASE + 0x0C))



/* bit fields*/
typedef union
{
	vuint32_t All_Fields;
	struct
	{
		vuint32_t reserved:13;
		vuint32_t p_13:1;
	}pin;
}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0C);

void* _sbrk(int incr)
{
	static uint8_t* heap_ptr = NULL;
	uint8_t* prev_heap_ptr = NULL;
	extern uint32_t _E_bss; // symbol
	extern uint32_t _heap_End; // symbol
	// first time initialized
	if(heap_ptr == NULL)
		heap_ptr = (uint8_t*)&_E_bss;
	
	prev_heap_ptr = heap_ptr;
	//protect stack
	if((heap_ptr + incr) > (uint8_t*)&_heap_End)
	return (void*)NULL;
    //bokking incr size
	heap_ptr += incr;
	
	return (void*) prev_heap_ptr;
	
	
}


int main(void)
{   
	int* p = (int*)malloc(4);// allocate 4 bytes
	free(p); 
	SET_BIT( RCC_APB2ENR  , 2); // Enable clock RCC
	CLR_BIT( GPIOA_CRH , 20);// set 2 in bit 20/21/22/23
	SET_BIT( GPIOA_CRH , 21);
	CLR_BIT( GPIOA_CRH , 22);
	CLR_BIT( GPIOA_CRH , 23);

	while(1)
	{
 // Set port a pin 13
		SET_BIT( GPIOA_ODR , 13);
		//R_ODR->pin.p_13 = 1;
		for(int i = 0 ;i < 500 ; i++);
// Clear port a pin 13
		CLR_BIT( GPIOA_ODR , 13);
		//R_ODR->pin.p_13 = 0;
		for(int i = 0 ;i < 500 ; i++);
	}

	return 0;
}

